name: Run Publish

on:
  workflow_dispatch:   # מאפשר הפעלה ידנית
  schedule:            # ריצה אוטומטית
    - cron: '0 17 * * *'  # 17:00 UTC = 19:00 לפי ישראל
jobs:
  run_publish:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Publish EXE
        run: .\publish\Data_From_Html.exe
