name: Run Publish

on:
  workflow_dispatch:   # מאפשר הפעלה ידנית
  schedule:            # מאפשר ריצה לפי לוח זמנים
    - cron: '30 16 * * *'  # כל יום ב‑18:15 ישראל (UTC+2)

jobs:
  run_publish:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Publish EXE
        run: .\publish\Data_From_Html.exe
